version: 0.2

env:
  variables:
    SOLUTION: .\D3MkEntityTree.sln

phases:
  build:
    commands:
      - '& "C:\Program Files (x86)\MSBuild\14.0\Bin\MSBuild.exe" $env:SOLUTION'
artifacts:
  files:
    - .\D3MkEntityTree\bin\Debug\*
